//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace info
{


    public partial class SystemConfig
    {
        

        
        
            protected global::System.Web.UI.WebControls.TextBox DeviceName;
            protected global::System.Web.UI.WebControls.DropDownList Processor;
            protected global::System.Web.UI.WebControls.DropDownList InstalledRAM;
            protected global::System.Web.UI.WebControls.DropDownList SystemType;
            protected global::System.Web.UI.WebControls.DropDownList SystemVersion;
            protected global::System.Web.UI.WebControls.Button SubmitButton;
        }
    }


